"""
Crew Local Saver Configuration.

This package contains YAML configuration files for the crew local saver,
defining agents and tasks for local file saving and persistence operations.

Files
-----
agents.yaml : file
    Configuration for local saving agents responsible for file
    management and persistence operations.
tasks.yaml : file
    Task definitions for local file saving workflow.

Notes
-----
The crew local saver handles the persistence of results, reports,
and other outputs generated by the various crews in the system,
ensuring data is properly saved and accessible for future use.
"""
